site_name: CI Demo
theme:
  name: material
  features:
    - content.code.copy
    - search.suggest
    - navigation.tabs
    - navigation.sections
    - content.code.annotate
plugins:
  - search
  - mkdocstrings
markdown_extensions:
  - pymdownx.superfences
  - admonition
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true
extra:
  version:
    provider: mike
