site_name: CI Demo
theme:
  name: readthedocs
  highlightjs: true
  include_homepage_in_sidebar: true
  prev_next_buttons_location: bottom
plugins:
  - search:
  - mkdocstrings:
      custom_templates: templates
extra:
  version:
    provider: mike
