name: Test Package

on:
  workflow_dispatch:
  workflow_call:
  push:

jobs:
  discover:
    name: Discover Microservices
    runs-on: ubuntu-latest
    steps:
      - name: Example discover
        run: echo "This is an example for microservices discovery"

  test:
    name: Test Microservices
    runs-on: ubuntu-latest
    needs: [ discover ]

    strategy:
      matrix:
        services: [ 'app1', 'app2', 'app3' ]

    steps:
      - name: Example tests
        run: echo "This is an example for microservices testing"

  report-status:
    name: Report Test Status
    if: always()
    needs: [ test ]
    runs-on: ubuntu-latest

    steps:
      - name: Check build status
        if: ${{ contains(needs.*.result, 'failure') }}
        run: exit 1
