name: Publish Documentation

on:
  workflow_call:

jobs:
  deploy:
    name: Deploy Documentation
    runs-on: ubuntu-latest
    steps:
      - name: Documentation deploy
        run: echo "This is an example documentation deployment"
